### ISSUE TITLE
Position absolute stops slider drag

### ISSUE THREAD

**Issue by gregg-cbs** [riyaddecoder/react-audio-play#1]
Hey!

Thanks for this player!

I have noticed when i make the player position absolute the slider drag stops working.

I cant see why. All the other controls work but i cant slide the slider.

```
.react-audio-player {
  z-index: 30;
  position: absolute;
}
```

**Comment by riyaddecoder** [comment]
@gregg-cbs Thank you for trying the package! I appreciate you reporting any issues you encounter. I apologize for the delayed update; I've been quite busy with my full-time job recently.

**Comment by gregg-cbs** [comment]
No worries! Thanks for contributing to the community. I have since moved onto using Svelte so unfortunately i do not get to experience your nice fix :( but next React project for sure.
