### ISSUE TITLE
Stop the current play

### ISSUE THREAD

**Issue by kair0span** [riyaddecoder/react-audio-play#8]
How to stop the current play if the user hit another play button in a song list?

**Comment by abdullahIsa** [comment]
Hello looking for how to do this too, anyway to get the ref ?

**Comment by riyaddecoder** [comment]
Hi! @mkireva @abdullahIsa  I've added ref props to give you control over the audio player—you can now play, pause, stop, and even focus on the audio with ease. Looking ahead, I am planning to introduce a group play system to manage playlists, similar to the voice list feature in WhatsApp. Checkout the [example here](https://riyaddecoder.github.io/react-audio-play/examples.html#example-4-usage-with-ref-available-from-v1-0-4)
